kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim
spec:
  accessModes:
    #look for any volume with RW once access mode
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
