apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: nginx-pod
  name: nginx-pod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: nginx-pod
  type: NodePort
status:
  loadBalancer: {}
