apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lab5-nginx
  name: lab5-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab5-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lab5-nginx
    spec:
      containers:
      - image: nginx:1.8
        name: nginx
        resources: {}
status: {}
